//! The description of a namespace schema.
//!
//! A schema is a **compile-time** entity: it belongs to a microservice's code
//! and describes which events, metrics and spans it can write. Nothing of it
//! reaches the disk except the version number in the segment header: levels,
//! text templates, tags and names are resolved at read time from identifiers.
//!
//! The descriptors are static (`&'static`), so a schema costs nothing at
//! runtime and lies wholly in the firmware's `.rodata`.
//!
//! Identifiers are assigned **explicitly**. The prototype's positional
//! auto-numbering silently remapped historical records onto the wrong decoders
//! when an event was inserted into the middle of a list; that mistake must not
//! be possible here, and renaming and renumbering are done by migrations.

use dduroc_format::{EventId, Level, MetricId, ProtocolVersion, SpanKindId, ValueType};

/// The storage class: the channel records of this type land in.
///
/// The channel determines the durability policy and the budget. Data that
/// matters declares [`StorageClass::Critical`], the rest
/// [`StorageClass::Default`].
///
/// An enum rather than a name in a string: the set of classes is closed (both
/// the schema macro and the store configuration know it), and a class that
/// does not exist must not be representable — with a string, a typo in the
/// configuration would silently create an orphan channel with its own policy.
/// A channel's directory name is [`StorageClass::as_str`], derived from the
/// class rather than a second source of it.
///
/// Closed in the `#[non_exhaustive]` sense too: a new class is not the
/// addition of a variant but a coordinated edit to the macro's `store:`
/// keyword, to [`StorageClass::ALL`], to the quotas and to the directory
/// layout. That breaks the build in any case, and forcing every match on a
/// class to carry a `_` arm for its sake would mean paying for something that
/// will not pass silently anyway.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum StorageClass {
    /// Batches with deferred syncing.
    Default,
    /// Syncing at once (group commit) — resilience to a power loss.
    Critical,
    /// A separate channel for telemetry: usually the largest budget.
    Telemetry,
}

impl StorageClass {
    /// Every class — for configuring and validating each of them.
    pub const ALL: [StorageClass; 3] = [Self::Default, Self::Critical, Self::Telemetry];

    /// The channel's directory name.
    pub const fn as_str(self) -> &'static str {
        match self {
            StorageClass::Default => "default",
            StorageClass::Critical => "critical",
            StorageClass::Telemetry => "telemetry",
        }
    }

    /// The position in [`StorageClass::ALL`] — a stable index for per-class
    /// tables (budget groups, quotas).
    pub const fn index(self) -> usize {
        match self {
            StorageClass::Default => 0,
            StorageClass::Critical => 1,
            StorageClass::Telemetry => 2,
        }
    }

    /// The class by its directory name — the inverse of
    /// [`StorageClass::as_str`].
    ///
    /// `None` means the directory is not the channel of any class this build
    /// knows: either a foreign directory or a dump from a future version with a
    /// new class. A reader has to tell them apart and say so rather than parse
    /// the unknown.
    pub fn from_dir_name(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|c| c.as_str() == name)
    }
}

impl std::fmt::Display for StorageClass {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A template language code (`"en"`, `"ru"`, `"ja"`…).
///
/// The set of languages is chosen by the application: `en`/`ru` is one
/// project's particular case, another needs `en`+`ja`+`zh`. The library is
/// agnostic to the set.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Language(pub &'static str);

impl Language {
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

/// A field of an event payload — for showing structured data at read time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FieldDesc {
    pub name: &'static str,
    /// The type name as in the source (`"f32"`, `"String"`) — for the UI.
    pub type_name: &'static str,
}

/// A payload decoding error.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("the payload does not match the event schema")]
pub struct DecodeError;

/// The decoding functions generated by the schema macro.
///
/// The signatures are deliberately free of `serde_json` and other such types:
/// the engine must not drag in the presentation layer's dependencies, and
/// generated code is free to use whatever it likes.
#[derive(Clone, Copy)]
pub struct EventDecoders {
    /// Render a message in the language at this index in [`Schema::languages`].
    pub render: fn(&[u8], usize) -> Result<String, DecodeError>,
    /// The payload fields as a JSON object.
    pub json: fn(&[u8]) -> Result<String, DecodeError>,
}

impl std::fmt::Debug for EventDecoders {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("EventDecoders { .. }")
    }
}

/// A message type.
#[derive(Debug, Clone, Copy)]
pub struct EventDesc {
    pub id: EventId,
    pub name: &'static str,
    /// The level is a static property of the type and is never written to disk.
    pub level: Level,
    pub class: StorageClass,
    /// Static category tags. They live in the schema and take no room on disk,
    /// so filtering by them is free: it reduces to picking a set of identifiers
    /// before any scanning.
    pub tags: &'static [&'static str],
    /// The templates — one per language of [`Schema::languages`], in the same
    /// order.
    pub templates: &'static [&'static str],
    pub fields: &'static [FieldDesc],
    pub decoders: Option<EventDecoders>,
}

impl EventDesc {
    pub fn template(&self, lang_index: usize) -> Option<&'static str> {
        self.templates.get(lang_index).copied()
    }
}

/// How much a metric value calls for attention.
///
/// Computed at read time from the limits and never written to disk: limits are
/// a configurable property of the installation, not a property of the
/// measurement. One and the same temperature is normal for one amplifier and
/// critical for another.
///
/// The word `critical` is deliberately **not** used here: it is taken by the
/// storage class ([`StorageClass::Critical`] — resilience to a power loss).
/// Those are different axes: the storage class says *how to write*, the
/// severity *what the value means*, and in a metric declaration they stand
/// side by side. The pair `warn` → `alarm` is familiar in industrial telemetry
/// and is not confused with it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default, Hash)]
pub enum Severity {
    #[default]
    Normal,
    /// The quantity has left what is normal.
    Warn,
    /// The quantity has left what is permissible — a fault.
    Alarm,
}

impl Severity {
    pub const fn as_str(self) -> &'static str {
        match self {
            Severity::Normal => "normal",
            Severity::Warn => "warn",
            Severity::Alarm => "alarm",
        }
    }

    pub const fn is_normal(self) -> bool {
        matches!(self, Severity::Normal)
    }
}

/// How a quantity behaves between samples — a hint for whoever draws it.
///
/// Points may be joined by a straight line only for a continuous quantity. A
/// state does **not** change between samples: a line through intermediate
/// values would show states that never were. The difference is not cosmetic, so
/// the kind is declared in the schema rather than guessed from the value type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Hash)]
pub enum MetricKind {
    /// A continuous quantity: temperature, power. Interpolated.
    #[default]
    Gauge,
    /// A discrete state: held as a step until the next sample.
    State,
    /// A monotonically growing counter: the derivative is meaningful, the value
    /// is not.
    Counter,
}

/// One state of an enum metric.
///
/// The code is written to disk as an ordinary integer while the name and the
/// severity stay in the schema — exactly as a message's level and template do.
/// The codes are assigned **explicitly**: positional numbering would shift
/// when a state was inserted into the middle of a list, and old segments would
/// start reading wrongly without a single sign of an error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StateDesc {
    pub code: u64,
    pub name: &'static str,
    /// The severity of merely being in this state.
    pub severity: Severity,
}

/// A range of permissible values; `None` means the bound is not set.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Range {
    pub min: Option<f64>,
    pub max: Option<f64>,
}

impl Range {
    pub const NONE: Self = Self {
        min: None,
        max: None,
    };

    pub const fn is_unset(&self) -> bool {
        self.min.is_none() && self.max.is_none()
    }

    /// Whether a value lies inside (the bounds are inclusive).
    ///
    /// NaN is inside no range: comparisons with it are false, and that is the
    /// right answer — an unknown value is not "normal".
    pub fn contains(&self, v: f64) -> bool {
        if v.is_nan() {
            return false;
        }
        self.min.is_none_or(|m| v >= m) && self.max.is_none_or(|m| v <= m)
    }
}

impl<R: std::ops::RangeBounds<f64>> From<R> for Range {
    /// A range from an ordinary range expression: `..=70.0`, `1.0..=1.5`,
    /// `10.0..`.
    ///
    /// A metric range's bounds are inclusive — beyond them it is no longer
    /// normal — and `Excluded` cannot be expressed for an `f64` without an
    /// arbitrary epsilon, so an exclusive bound is treated as inclusive. In a
    /// schema the macro demands an explicit `..=`; here that cannot be
    /// demanded, but at least nothing is silently misrepresented.
    fn from(r: R) -> Self {
        use std::ops::Bound;
        let bound = |b: Bound<&f64>| match b {
            Bound::Unbounded => None,
            Bound::Included(v) | Bound::Excluded(v) => Some(*v),
        };
        Self {
            min: bound(r.start_bound()),
            max: bound(r.end_bound()),
        }
    }
}

/// The limits of a numeric metric: the ranges **outside** which a value calls
/// for attention.
///
/// `alarm` has to contain `warn`: a quantity first leaves what is normal, then
/// what is permissible. The reverse would mean a value is a fault without
/// being a warning. Checked in [`Schema::validate`].
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Thresholds {
    /// Outside this range — [`Severity::Warn`].
    pub warn: Range,
    /// Outside this one — [`Severity::Alarm`].
    pub alarm: Range,
}

impl Thresholds {
    pub const NONE: Self = Self {
        warn: Range::NONE,
        alarm: Range::NONE,
    };

    /// Limits from two range expressions — just as in a schema declaration:
    ///
    /// ```text
    /// Thresholds::new(..=70.0, ..=85.0)        // from above only
    /// Thresholds::new(1.0..=1.5, 1.0..=2.0)    // from both sides
    /// ```
    pub fn new(
        warn: impl std::ops::RangeBounds<f64>,
        alarm: impl std::ops::RangeBounds<f64>,
    ) -> Self {
        Self {
            warn: warn.into(),
            alarm: alarm.into(),
        }
    }

    pub const fn is_unset(&self) -> bool {
        self.warn.is_unset() && self.alarm.is_unset()
    }

    /// The severity of a numeric value. The heavier diagnosis wins.
    pub fn severity_of(&self, v: f64) -> Severity {
        if !self.alarm.is_unset() && !self.alarm.contains(v) {
            return Severity::Alarm;
        }
        if !self.warn.is_unset() && !self.warn.contains(v) {
            return Severity::Warn;
        }
        Severity::Normal
    }
}

/// A telemetry metric type.
#[derive(Debug, Clone, Copy)]
pub struct MetricDesc {
    pub id: MetricId,
    pub name: &'static str,
    pub value_type: ValueType,
    pub class: StorageClass,
    /// The unit for the UI (`"°C"`, `"dBm"`).
    pub unit: &'static str,
    /// Static category tags — as on [`EventDesc::tags`]. They live in the
    /// schema and take no room on disk.
    ///
    /// A metric has no runtime dimensions: a series is identified by its
    /// metric. Four temperature sensors are four schema metrics rather than one
    /// with a tag, or the tag would have to be written into every sample.
    pub tags: &'static [&'static str],
    /// How the quantity behaves between samples.
    pub kind: MetricKind,
    /// The labels of the state codes. Empty means the metric is not an enum.
    pub states: &'static [StateDesc],
    /// The default limits. An installation may override them at runtime (see
    /// `Namespace::set_limits`) — on learning the hardware model, for instance.
    pub thresholds: Thresholds,
    /// The warning trigger predicate: true means the value is a warning.
    ///
    /// For shapes a normal range cannot express. The polarity is the opposite
    /// of [`MetricDesc::thresholds`] — hence the separate
    /// `warn_if:`/`alarm_if:` keys in a schema. It composes with ranges by the
    /// rule "the heaviest diagnosis wins"; it offers no introspection, and
    /// chart bands are drawn from ranges alone.
    pub warn_if: Option<fn(f64) -> bool>,
    /// The fault trigger predicate — see [`MetricDesc::warn_if`].
    pub alarm_if: Option<fn(f64) -> bool>,
}

impl MetricDesc {
    /// The label of a state by its code. `None` means the code is not declared
    /// or the metric is not an enum.
    pub fn state(&self, code: u64) -> Option<&'static StateDesc> {
        self.states.iter().find(|s| s.code == code)
    }

    /// A value's severity by the limits **from the schema**.
    ///
    /// For enums and `bool` the state's severity is taken: their values are not
    /// ordered, and "above the threshold" does not apply. An unfamiliar code is
    /// no cause for alarm in itself, but it is not normal either: it has no
    /// label, and a reader has nothing to decide its meaning with.
    pub fn severity_of(&self, value: &dduroc_format::Value<'_>) -> Severity {
        use dduroc_format::Value;
        if !self.states.is_empty() {
            let code = match value {
                Value::U64(v) => Some(*v),
                Value::I64(v) if *v >= 0 => Some(*v as u64),
                Value::Bool(b) => Some(u64::from(*b)),
                _ => None,
            };
            return code
                .and_then(|c| self.state(c))
                .map_or(Severity::Normal, |s| s.severity);
        }
        value.as_f64().map_or(Severity::Normal, |v| {
            self.numeric_severity(&self.thresholds, v)
        })
    }

    /// A number's severity by ranges and predicates; the ranges may be a
    /// runtime override, the predicates are always the schema's.
    pub(crate) fn numeric_severity(&self, thresholds: &Thresholds, v: f64) -> Severity {
        let by_predicate = if self.alarm_if.is_some_and(|hit| hit(v)) {
            Severity::Alarm
        } else if self.warn_if.is_some_and(|hit| hit(v)) {
            Severity::Warn
        } else {
            Severity::Normal
        };
        thresholds.severity_of(v).max(by_predicate)
    }
}

/// A span kind.
#[derive(Debug, Clone, Copy)]
pub struct SpanDesc {
    pub id: SpanKindId,
    pub name: &'static str,
    pub class: StorageClass,
}

/// The migration step `from → from + 1`.
#[derive(Clone, Copy)]
pub struct Migration {
    /// The version being migrated from.
    pub from: u16,
    /// The step touches any segment whatever it holds.
    ///
    /// `true` means the affected types are not declared and cannot be decided
    /// from. This is a **safe default**: rewriting a segment needlessly costs
    /// exactly one flash write cycle, while skipping one that mattered leaves
    /// it in the earlier layout forever, and silently at that.
    pub touches_all: bool,
    /// The types the step affects. Segments holding none of them need not be
    /// rewritten — a direct saving of flash wear.
    pub events: &'static [EventId],
    pub metrics: &'static [MetricId],
    /// The span kinds the step affects.
    ///
    /// Unlike events and metrics, they save no segments: there is no set of
    /// span kinds in the footer, and there is nothing to answer "this segment
    /// holds no such spans" from. A step with spans always rewrites the segment
    /// — see [`Migration::touches`].
    pub spans: &'static [SpanKindId],
    /// The transformation of one record. `Ok(None)` deletes the record.
    pub migrate: fn(MigrationInput<'_>) -> Result<Option<MigrationOutcome>, DecodeError>,
}

impl Migration {
    /// Whether a segment with this footer needs rewriting.
    ///
    /// The only place this question is decided: the type sets in the footer
    /// answer it without reading any blocks, and `touches_all` without reading
    /// at all.
    pub fn touches(&self, footer: &dduroc_format::Footer) -> bool {
        // A step that touches span kinds rewrites the segment unconditionally.
        // The footer knows the sets of events and metrics but not of spans:
        // there is nobody to ask "is there such a span here", and deciding "no"
        // on a guess would leave those records in the earlier layout forever —
        // silently at that, because the run reports success and stamps the
        // metadata. A needless rewrite costs one flash cycle; a skip is
        // irreversible.
        self.touches_all || !self.spans.is_empty() || footer.touches(self.events, self.metrics)
    }
}

impl std::fmt::Debug for Migration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Migration")
            .field("from", &self.from)
            .field("touches_all", &self.touches_all)
            .field("events", &self.events)
            .field("metrics", &self.metrics)
            .field("spans", &self.spans)
            .finish_non_exhaustive()
    }
}

/// The input to a migration step: a record **in the earlier layout**, as it
/// lies on disk.
///
/// It pairs with [`MigrationOutcome`], which is what the step returns. The
/// names are kept apart deliberately: a participle ("a migrated record") would
/// flip the sides of the signature, whereas a step receives exactly what has
/// not been brought up to date.
#[derive(Debug, Clone, Copy)]
pub struct MigrationInput<'a> {
    pub record: dduroc_format::Record<'a>,
}

impl MigrationInput<'_> {
    /// The message type. `None` means the record is not a message.
    pub fn event_id(&self) -> Option<EventId> {
        match &self.record {
            dduroc_format::Record::Message(m) => Some(m.event),
            _ => None,
        }
    }

    /// The sample's metric. `None` means the record is not a sample.
    pub fn metric_id(&self) -> Option<MetricId> {
        match &self.record {
            dduroc_format::Record::Sample(s) => Some(s.metric),
            _ => None,
        }
    }

    /// The span kind. `None` means the record is not the start of a span.
    ///
    /// A span's end has no kind: it refers by number to one already started,
    /// and renaming a kind does not concern it.
    pub fn span_kind(&self) -> Option<SpanKindId> {
        match &self.record {
            dduroc_format::Record::SpanStart(s) => Some(s.kind),
            _ => None,
        }
    }

    /// The sample's value. `None` means the record is not a sample.
    ///
    /// The value is self-describing: the type lies in the record itself rather
    /// than being taken from the schema. So a step sees what was written — even
    /// if the schema has since declared a different type for the metric.
    pub fn value(&self) -> Option<dduroc_format::Value<'_>> {
        match &self.record {
            dduroc_format::Record::Sample(s) => Some(s.value),
            _ => None,
        }
    }

    /// The message's raw payload. `None` means the record is not a message.
    ///
    /// An id remap needs it: the type changes its number while the field bytes
    /// travel as they are.
    pub fn payload(&self) -> Option<&[u8]> {
        match &self.record {
            dduroc_format::Record::Message(m) => Some(m.payload),
            _ => None,
        }
    }

    /// Parse a message payload into the old layout.
    ///
    /// `T` is a struct with the fields of the version the step migrates from
    /// (with a declared `history` the macro generates it). It is an error for a
    /// record that is not a message too: the other kinds have no payload in
    /// this sense.
    pub fn decode<T: serde::de::DeserializeOwned>(&self) -> Result<T, DecodeError> {
        match &self.record {
            dduroc_format::Record::Message(m) => {
                postcard::from_bytes(m.payload).map_err(|_| DecodeError)
            }
            _ => Err(DecodeError),
        }
    }
}

/// The outcome of a migration step — what the record is to become. An owning
/// form: a step usually re-encodes the payload.
///
/// It pairs with [`MigrationInput`]. The former name `OwnedRecord` collided
/// with the reader's type of the same name (an owning copy of a wire record) —
/// importing both crates made them indistinguishable.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum MigrationOutcome {
    /// Leave it as it is.
    AsIs,
    /// Replace a message's type and/or payload.
    Message { event: EventId, payload: Vec<u8> },
    /// Replace a sample's metric without touching the value.
    ///
    /// It stays a separate outcome for the value's sake: a remap does not copy
    /// it at all, and a megabyte spectrum would cost a copy on every record.
    SampleMetric(MetricId),
    /// Replace a sample's value (and its metric if need be).
    ///
    /// The value owns its bytes: a step's outcome has no lifetime tying it to
    /// the input record, so it has nothing to borrow the block's bytes from.
    Sample {
        metric: MetricId,
        value: crate::staged::OwnedValue,
    },
    /// Rename a span kind.
    ///
    /// The kind only: a span's number and its parent are the record's identity,
    /// referred to by its messages and its child spans, and a chain has no way
    /// to rewrite those references.
    SpanKind(SpanKindId),
}

/// A namespace schema.
#[derive(Debug, Clone, Copy)]
pub struct Schema {
    /// The schema's identity. A namespace remembers it and refuses to open
    /// under a foreign one: equal event ids in different schemas mean different
    /// things.
    pub name: &'static str,
    pub version: ProtocolVersion,
    pub languages: &'static [Language],
    pub events: &'static [EventDesc],
    pub metrics: &'static [MetricDesc],
    pub spans: &'static [SpanDesc],
    pub migrations: &'static [Migration],
}

/// The kind of schema descriptor — whose identifier space is meant.
///
/// An enum rather than a string: events, metrics and spans have separate id
/// spaces, and diagnostics that named the kind with a string would let one
/// name a kind that does not exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DescriptorKind {
    Event,
    Metric,
    Span,
}

impl DescriptorKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            DescriptorKind::Event => "event",
            DescriptorKind::Metric => "metric",
            DescriptorKind::Span => "span",
        }
    }
}

impl std::fmt::Display for DescriptorKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A schema validation error: caught when a namespace comes up, that is, at
/// process start rather than a month later over unreadable logs.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum SchemaError {
    #[error("schema {schema:?}: {kind} id {id} is declared twice ({first:?} and {second:?})")]
    DuplicateId {
        schema: &'static str,
        kind: DescriptorKind,
        id: u16,
        first: &'static str,
        second: &'static str,
    },

    #[error(
        "schema {schema:?}: event {event:?} has {got} templates but {want} languages are declared"
    )]
    TemplateCount {
        schema: &'static str,
        event: &'static str,
        got: usize,
        want: usize,
    },

    #[error(
        "schema {schema:?}: no languages declared — there would be nothing to render messages with"
    )]
    NoLanguages { schema: &'static str },

    #[error("schema {schema:?}: language {lang:?} is declared twice")]
    DuplicateLanguage {
        schema: &'static str,
        lang: &'static str,
    },

    #[error("schema {schema:?}: version 0 is not allowed — version numbering starts at 1")]
    ZeroVersion { schema: &'static str },

    #[error(
        "schema {schema:?}: no migration step from version {from} (the chain has to be \
         unbroken up to the current version {version})"
    )]
    MigrationGap {
        schema: &'static str,
        from: u16,
        version: u16,
    },

    #[error("schema {schema:?}: the migration step from version {from} is declared twice")]
    DuplicateMigration { schema: &'static str, from: u16 },

    #[error("schema {schema:?}: the name is empty")]
    EmptyName { schema: &'static str },

    #[error(
        "schema {schema:?}: {kind} {name:?} breaks the identifier ordering — the \
         descriptor search is binary and requires ascending order"
    )]
    Unsorted {
        schema: &'static str,
        kind: DescriptorKind,
        name: &'static str,
    },

    #[error("schema {schema:?}: metric {metric:?} declares state code {code} twice")]
    DuplicateStateCode {
        schema: &'static str,
        metric: &'static str,
        code: u64,
    },

    #[error("schema {schema:?}: metric {metric:?}: {reason}")]
    BadMetric {
        schema: &'static str,
        metric: &'static str,
        reason: &'static str,
    },
}

impl Schema {
    /// Check the schema's internal consistency.
    pub fn validate(&self) -> Result<(), SchemaError> {
        if self.name.is_empty() {
            return Err(SchemaError::EmptyName { schema: self.name });
        }
        if self.version.0 == 0 {
            return Err(SchemaError::ZeroVersion { schema: self.name });
        }
        if self.languages.is_empty() {
            return Err(SchemaError::NoLanguages { schema: self.name });
        }
        for (i, a) in self.languages.iter().enumerate() {
            if self.languages[..i].contains(a) {
                return Err(SchemaError::DuplicateLanguage {
                    schema: self.name,
                    lang: a.0,
                });
            }
        }

        check_unique(
            self.name,
            DescriptorKind::Event,
            self.events.iter().map(|e| (e.id.0, e.name)),
        )?;
        check_unique(
            self.name,
            DescriptorKind::Metric,
            self.metrics.iter().map(|m| (m.id.0, m.name)),
        )?;
        check_unique(
            self.name,
            DescriptorKind::Span,
            self.spans.iter().map(|s| (s.id.0, s.name)),
        )?;

        // The descriptors have to run in ascending order of identifier: the
        // search over them is binary and happens on every record. The `schema!`
        // macro lays them out itself, but a schema can also be declared by
        // hand.
        check_sorted(
            self.name,
            DescriptorKind::Event,
            self.events.iter().map(|e| (e.id.0, e.name)),
        )?;
        check_sorted(
            self.name,
            DescriptorKind::Metric,
            self.metrics.iter().map(|m| (m.id.0, m.name)),
        )?;
        check_sorted(
            self.name,
            DescriptorKind::Span,
            self.spans.iter().map(|s| (s.id.0, s.name)),
        )?;

        for e in self.events {
            if e.templates.len() != self.languages.len() {
                return Err(SchemaError::TemplateCount {
                    schema: self.name,
                    event: e.name,
                    got: e.templates.len(),
                    want: self.languages.len(),
                });
            }
        }

        for m in self.metrics {
            self.check_metric(m)?;
        }

        // The migration chain has to be unbroken: 1→2→…→version. A gap means
        // data of an old version would silently remain misinterpreted.
        for (i, m) in self.migrations.iter().enumerate() {
            if self.migrations[..i].iter().any(|p| p.from == m.from) {
                return Err(SchemaError::DuplicateMigration {
                    schema: self.name,
                    from: m.from,
                });
            }
        }
        for from in 1..self.version.0 {
            if !self.migrations.iter().any(|m| m.from == from) {
                return Err(SchemaError::MigrationGap {
                    schema: self.name,
                    from,
                    version: self.version.0,
                });
            }
        }
        Ok(())
    }

    /// Check that a metric makes sense.
    ///
    /// A meaningless metric cannot be declared: the error is caught at process
    /// start rather than a month later over a chart nobody can read.
    fn check_metric(&self, m: &MetricDesc) -> Result<(), SchemaError> {
        let bad = |reason| SchemaError::BadMetric {
            schema: self.name,
            metric: m.name,
            reason,
        };

        // Being an enum and being of kind State are one and the same property
        // declared twice. A discrepancy means one of the two was written by
        // mistake, and only the schema's author knows which.
        match (m.states.is_empty(), m.kind) {
            (true, MetricKind::State) => {
                return Err(bad(
                    "kind State with no declared states: there is nothing to label with",
                ));
            }
            (false, k) if k != MetricKind::State => {
                return Err(bad(
                    "states are declared but the kind is not State — a chart would be \
                     drawn as a straight line through values that never were",
                ));
            }
            _ => {}
        }

        if !m.states.is_empty() {
            // A state code is an integer on disk, so a fractional or blob value
            // type does not apply to an enum.
            if !matches!(
                m.value_type,
                ValueType::U64 | ValueType::I64 | ValueType::Bool
            ) {
                return Err(bad(
                    "states are allowed only on an integer or boolean metric: a \
                     state code is stored as an integer",
                ));
            }
            if !m.thresholds.is_unset() {
                return Err(bad(
                    "numeric limits on an enum: its values are not ordered, and \
                     severity is set per state",
                ));
            }
            if m.warn_if.is_some() || m.alarm_if.is_some() {
                return Err(bad(
                    "predicates on an enum: its values are not ordered, and severity \
                     is set per state",
                ));
            }
            for (i, s) in m.states.iter().enumerate() {
                if m.states[..i].iter().any(|p| p.code == s.code) {
                    return Err(SchemaError::DuplicateStateCode {
                        schema: self.name,
                        metric: m.name,
                        code: s.code,
                    });
                }
                if s.name.is_empty() {
                    return Err(bad("a state with no name"));
                }
                if m.value_type == ValueType::Bool && s.code > 1 {
                    return Err(bad("a boolean metric allows only the codes 0 and 1"));
                }
            }
        }

        for (r, what) in [
            (m.thresholds.warn, "warning"),
            (m.thresholds.alarm, "alarm"),
        ] {
            if matches!((r.min, r.max), (Some(lo), Some(hi)) if lo > hi) {
                let _ = what;
                return Err(bad("the range is inverted: min exceeds max"));
            }
            if r.min.is_some_and(f64::is_nan) || r.max.is_some_and(f64::is_nan) {
                return Err(bad(
                    "a range bound is NaN: comparisons with it are always false",
                ));
            }
        }
        crate::limits::check_nesting(m.name, &m.thresholds).map_err(|_| {
            bad(
                "the alarm range has to contain the warning one: otherwise a value \
                 would be a fault without being a warning",
            )
        })?;

        if m.value_type == ValueType::Blob && (m.warn_if.is_some() || m.alarm_if.is_some()) {
            return Err(bad(
                "a predicate on a blob metric: the value cannot be reduced to a \
                 number, so there is nothing for it to check",
            ));
        }

        Ok(())
    }

    /// Find a message type by its identifier.
    ///
    /// Called on **every** record written and read, so the search is binary: a
    /// linear walk over two hundred-odd descriptors per event is noticeable
    /// already on x86, let alone on armv7. The ordering is checked in
    /// [`Schema::validate`] rather than assumed.
    pub fn event(&self, id: EventId) -> Option<&'static EventDesc> {
        match self.events.binary_search_by_key(&id.0, |e| e.id.0) {
            Ok(i) => Some(&self.events[i]),
            // The schema is not sorted (it never passed validate) — search
            // honestly.
            Err(_) => self.events.iter().find(|e| e.id == id),
        }
    }

    pub fn metric(&self, id: MetricId) -> Option<&'static MetricDesc> {
        self.metric_index(id).map(|(_, d)| d)
    }

    /// A metric together with its position in [`Schema::metrics`].
    ///
    /// The position is a stable key for what is stored alongside the schema and
    /// never written to disk: the runtime limits (see [`crate::limits`]).
    pub fn metric_index(&self, id: MetricId) -> Option<(usize, &'static MetricDesc)> {
        match self.metrics.binary_search_by_key(&id.0, |m| m.id.0) {
            Ok(i) => Some((i, &self.metrics[i])),
            // The schema is not sorted (it never passed validate) — search
            // honestly.
            Err(_) => self
                .metrics
                .iter()
                .position(|m| m.id == id)
                .map(|i| (i, &self.metrics[i])),
        }
    }

    pub fn span(&self, id: SpanKindId) -> Option<&'static SpanDesc> {
        match self.spans.binary_search_by_key(&id.0, |s| s.id.0) {
            Ok(i) => Some(&self.spans[i]),
            Err(_) => self.spans.iter().find(|s| s.id == id),
        }
    }

    pub fn language_index(&self, code: &str) -> Option<usize> {
        self.languages.iter().position(|l| l.0 == code)
    }

    /// Every channel the schema may use.
    pub fn classes(&self) -> Vec<StorageClass> {
        // The ordinary channel always exists, even if no type declared it. Free
        // text has nowhere to get a class of its own — it has no type in the
        // schema — and it has to be written: it is the bridge from foreign
        // logs, the panic handler and the one-off announcement of a build
        // defect. A schema of pure telemetry would leave all of that without a
        // channel, and the very announcement the mechanism exists for would
        // fail silently.
        //
        // An empty channel costs almost nothing: the directory is created when
        // the namespace comes up, and a segment only by the first record.
        let mut out: Vec<StorageClass> = vec![StorageClass::Default];
        let all = self
            .events
            .iter()
            .map(|e| e.class)
            .chain(self.metrics.iter().map(|m| m.class))
            .chain(self.spans.iter().map(|s| s.class));
        for c in all {
            if !out.contains(&c) {
                out.push(c);
            }
        }
        out.sort_unstable();
        out
    }

    /// The migration step from version `from`.
    pub fn migration(&self, from: u16) -> Option<&'static Migration> {
        self.migrations.iter().find(|m| m.from == from)
    }
}

/// Check that identifiers ascend: the search over them is binary.
fn check_sorted(
    schema: &'static str,
    kind: DescriptorKind,
    items: impl Iterator<Item = (u16, &'static str)>,
) -> Result<(), SchemaError> {
    let mut prev: Option<u16> = None;
    for (id, name) in items {
        if prev.is_some_and(|p| id <= p) {
            return Err(SchemaError::Unsorted { schema, kind, name });
        }
        prev = Some(id);
    }
    Ok(())
}

fn check_unique(
    schema: &'static str,
    kind: DescriptorKind,
    items: impl Iterator<Item = (u16, &'static str)>,
) -> Result<(), SchemaError> {
    let mut seen: Vec<(u16, &'static str)> = Vec::new();
    for (id, name) in items {
        if let Some((_, first)) = seen.iter().find(|(i, _)| *i == id) {
            return Err(SchemaError::DuplicateId {
                schema,
                kind,
                id,
                first,
                second: name,
            });
        }
        seen.push((id, name));
    }
    Ok(())
}

/// Schema constructors for the tests of neighbouring modules.
///
/// Not `mod tests`: those need a ready instance, not checks of this module.
#[cfg(test)]
pub(crate) mod tests_support {
    use super::*;

    /// The minimal valid schema with migration steps.
    pub(crate) fn minimal_schema_with_migrations(
        version: u16,
        migrations: &'static [Migration],
    ) -> Schema {
        static LANGS: &[Language] = &[Language("en")];
        Schema {
            name: "probe",
            version: ProtocolVersion(version),
            languages: LANGS,
            events: &[],
            metrics: &[],
            spans: &[],
            migrations,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const LANGS: &[Language] = &[Language("en"), Language("ru")];

    fn schema(events: &'static [EventDesc], version: u16) -> Schema {
        Schema {
            name: "radio",
            version: ProtocolVersion(version),
            languages: LANGS,
            events,
            metrics: &[],
            spans: &[],
            migrations: &[],
        }
    }

    #[test]
    fn valid_schema_passes() {
        static EVENTS: &[EventDesc] = &[
            EventDesc {
                id: EventId(1),
                name: "PowerSet",
                level: Level::Info,
                class: StorageClass::Critical,
                tags: &["rf"],
                templates: &["power {dbm}", "мощность {dbm}"],
                fields: &[],
                decoders: None,
            },
            EventDesc {
                id: EventId(2),
                name: "Failed",
                level: Level::Error,
                class: StorageClass::Default,
                tags: &[],
                templates: &["failed", "сбой"],
                fields: &[],
                decoders: None,
            },
        ];
        let s = schema(EVENTS, 1);
        s.validate().expect("the schema is valid");
        assert_eq!(s.event(EventId(1)).unwrap().name, "PowerSet");
        assert!(s.event(EventId(99)).is_none());
        assert_eq!(s.language_index("ru"), Some(1));
        assert_eq!(s.language_index("ja"), None);
        // The order is as in the enum declaration: it determines the channel
        // indices at runtime, while on disk channels live under names.
        assert_eq!(
            s.classes(),
            vec![StorageClass::Default, StorageClass::Critical]
        );
        assert_eq!(
            s.event(EventId(1)).unwrap().template(1),
            Some("мощность {dbm}")
        );
    }

    #[test]
    fn the_default_channel_exists_even_if_no_type_asks_for_it() {
        // A schema of pure telemetry declares no ordinary channel, and free
        // text has nowhere else to go: it has no type in the schema and
        // therefore no storage class. Without an unconditional `default`, the
        // announcement of a build defect, a bridge message and the panic
        // handler would fail silently — that is, the mechanism set up against
        // silence would itself go quiet.
        static METRICS: &[MetricDesc] = &[MetricDesc {
            warn_if: None,
            alarm_if: None,
            id: MetricId(1),
            name: "Spectrum",
            unit: "",
            tags: &[],
            value_type: ValueType::Blob,
            kind: MetricKind::Gauge,
            class: StorageClass::Telemetry,
            states: &[],
            thresholds: Thresholds::NONE,
        }];
        let s = Schema {
            name: "telemetry-only",
            version: ProtocolVersion(1),
            languages: &[Language("en")],
            events: &[],
            metrics: METRICS,
            spans: &[],
            migrations: &[],
        };
        s.validate().expect("the schema is valid");
        assert_eq!(
            s.classes(),
            vec![StorageClass::Default, StorageClass::Telemetry],
            "the ordinary channel always exists"
        );
    }

    #[test]
    fn duplicate_ids_rejected() {
        static EVENTS: &[EventDesc] = &[
            EventDesc {
                id: EventId(5),
                name: "A",
                level: Level::Info,
                class: StorageClass::Default,
                tags: &[],
                templates: &["a", "а"],
                fields: &[],
                decoders: None,
            },
            EventDesc {
                id: EventId(5),
                name: "B",
                level: Level::Info,
                class: StorageClass::Default,
                tags: &[],
                templates: &["b", "б"],
                fields: &[],
                decoders: None,
            },
        ];
        let err = schema(EVENTS, 1).validate().unwrap_err();
        assert!(
            matches!(
                err,
                SchemaError::DuplicateId {
                    id: 5,
                    first: "A",
                    second: "B",
                    ..
                }
            ),
            "got {err}"
        );
    }

    #[test]
    fn template_count_must_match_languages() {
        static EVENTS: &[EventDesc] = &[EventDesc {
            id: EventId(1),
            name: "Only",
            level: Level::Info,
            class: StorageClass::Default,
            tags: &[],
            templates: &["english only"],
            fields: &[],
            decoders: None,
        }];
        let err = schema(EVENTS, 1).validate().unwrap_err();
        assert!(
            matches!(
                err,
                SchemaError::TemplateCount {
                    got: 1,
                    want: 2,
                    ..
                }
            ),
            "got {err}"
        );
    }

    #[test]
    fn migration_chain_must_be_continuous() {
        static EVENTS: &[EventDesc] = &[];
        fn noop(_: MigrationInput<'_>) -> Result<Option<MigrationOutcome>, DecodeError> {
            Ok(Some(MigrationOutcome::AsIs))
        }
        static STEPS: &[Migration] = &[Migration {
            from: 1,
            touches_all: true,
            events: &[],
            metrics: &[],
            spans: &[],
            migrate: noop,
        }];

        // Version 3, with only a 1→2 step: the gap is 2→3.
        let s = Schema {
            migrations: STEPS,
            ..schema(EVENTS, 3)
        };
        let err = s.validate().unwrap_err();
        assert!(
            matches!(
                err,
                SchemaError::MigrationGap {
                    from: 2,
                    version: 3,
                    ..
                }
            ),
            "got {err}"
        );

        // A complete chain passes.
        static FULL: &[Migration] = &[
            Migration {
                from: 1,
                touches_all: true,
                events: &[],
                metrics: &[],
                spans: &[],
                migrate: noop,
            },
            Migration {
                from: 2,
                touches_all: true,
                events: &[],
                metrics: &[],
                spans: &[],
                migrate: noop,
            },
        ];
        Schema {
            migrations: FULL,
            ..schema(EVENTS, 3)
        }
        .validate()
        .expect("an unbroken chain");
    }

    /// A schema with one metric — for checking that metrics make sense.
    fn with_metric(metrics: &'static [MetricDesc]) -> Schema {
        static EVENTS: &[EventDesc] = &[];
        Schema {
            metrics,
            ..schema(EVENTS, 1)
        }
    }

    const fn metric(
        value_type: ValueType,
        kind: MetricKind,
        states: &'static [StateDesc],
        thresholds: Thresholds,
    ) -> MetricDesc {
        MetricDesc {
            warn_if: None,
            alarm_if: None,
            id: MetricId(1),
            name: "m",
            value_type,
            class: StorageClass::Telemetry,
            unit: "",
            tags: &[],
            kind,
            states,
            thresholds,
        }
    }

    const fn range(min: Option<f64>, max: Option<f64>) -> Range {
        Range { min, max }
    }

    #[test]
    fn valid_state_metric_passes() {
        static STATES: &[StateDesc] = &[
            StateDesc {
                code: 0,
                name: "Los",
                severity: Severity::Alarm,
            },
            StateDesc {
                code: 2,
                name: "Lock",
                severity: Severity::Normal,
            },
        ];
        static M: &[MetricDesc] = &[metric(
            ValueType::U64,
            MetricKind::State,
            STATES,
            Thresholds::NONE,
        )];
        with_metric(M).validate().expect("the enum is valid");

        let desc = with_metric(M).metric(MetricId(1)).unwrap();
        assert_eq!(desc.state(0).unwrap().name, "Los");
        assert_eq!(desc.state(2).unwrap().severity, Severity::Normal);
        assert!(
            desc.state(1).is_none(),
            "code 1 is not declared, and there is no label"
        );
        // Gaps in the numbering are legitimate: the codes are explicit, not
        // positional.
        assert_eq!(
            desc.severity_of(&dduroc_format::Value::U64(2)),
            Severity::Normal
        );
    }

    #[test]
    fn state_and_kind_must_agree() {
        static STATES: &[StateDesc] = &[StateDesc {
            code: 0,
            name: "A",
            severity: Severity::Normal,
        }];

        // Kind State with no states: there is nothing to label with.
        static NO_STATES: &[MetricDesc] = &[metric(
            ValueType::U64,
            MetricKind::State,
            &[],
            Thresholds::NONE,
        )];
        assert!(matches!(
            with_metric(NO_STATES).validate(),
            Err(SchemaError::BadMetric { .. })
        ));

        // States with kind Gauge: a chart would be drawn as a straight line
        // through values that never were.
        static WRONG_KIND: &[MetricDesc] = &[metric(
            ValueType::U64,
            MetricKind::Gauge,
            STATES,
            Thresholds::NONE,
        )];
        assert!(matches!(
            with_metric(WRONG_KIND).validate(),
            Err(SchemaError::BadMetric { .. })
        ));
    }

    #[test]
    fn states_require_an_integral_value_type() {
        static STATES: &[StateDesc] = &[StateDesc {
            code: 0,
            name: "A",
            severity: Severity::Normal,
        }];
        for vt in [ValueType::F32, ValueType::F64, ValueType::Blob] {
            let leaked: &'static [MetricDesc] = Box::leak(Box::new([metric(
                vt,
                MetricKind::State,
                STATES,
                Thresholds::NONE,
            )]));
            assert!(
                matches!(
                    with_metric(leaked).validate(),
                    Err(SchemaError::BadMetric { .. })
                ),
                "type {vt:?} cannot carry a state code"
            );
        }
    }

    #[test]
    fn duplicate_and_nameless_states_rejected() {
        static DUP: &[StateDesc] = &[
            StateDesc {
                code: 5,
                name: "A",
                severity: Severity::Normal,
            },
            StateDesc {
                code: 5,
                name: "B",
                severity: Severity::Warn,
            },
        ];
        static M: &[MetricDesc] = &[metric(
            ValueType::U64,
            MetricKind::State,
            DUP,
            Thresholds::NONE,
        )];
        assert!(matches!(
            with_metric(M).validate(),
            Err(SchemaError::DuplicateStateCode { code: 5, .. })
        ));

        static NAMELESS: &[StateDesc] = &[StateDesc {
            code: 0,
            name: "",
            severity: Severity::Normal,
        }];
        static N: &[MetricDesc] = &[metric(
            ValueType::U64,
            MetricKind::State,
            NAMELESS,
            Thresholds::NONE,
        )];
        assert!(matches!(
            with_metric(N).validate(),
            Err(SchemaError::BadMetric { .. })
        ));
    }

    #[test]
    fn bool_states_are_limited_to_zero_and_one() {
        static BAD: &[StateDesc] = &[StateDesc {
            code: 7,
            name: "Weird",
            severity: Severity::Normal,
        }];
        static M: &[MetricDesc] = &[metric(
            ValueType::Bool,
            MetricKind::State,
            BAD,
            Thresholds::NONE,
        )];
        assert!(matches!(
            with_metric(M).validate(),
            Err(SchemaError::BadMetric { .. })
        ));

        static OK: &[StateDesc] = &[
            StateDesc {
                code: 0,
                name: "Unlocked",
                severity: Severity::Alarm,
            },
            StateDesc {
                code: 1,
                name: "Locked",
                severity: Severity::Normal,
            },
        ];
        static G: &[MetricDesc] = &[metric(
            ValueType::Bool,
            MetricKind::State,
            OK,
            Thresholds::NONE,
        )];
        with_metric(G).validate().expect("a bool as two states");
        // A boolean's severity comes from the state.
        let d = with_metric(G).metric(MetricId(1)).unwrap();
        assert_eq!(
            d.severity_of(&dduroc_format::Value::Bool(false)),
            Severity::Alarm
        );
        assert_eq!(
            d.severity_of(&dduroc_format::Value::Bool(true)),
            Severity::Normal
        );
    }

    #[test]
    fn thresholds_must_be_sane() {
        // An inverted range.
        static INVERTED: &[MetricDesc] = &[metric(
            ValueType::F32,
            MetricKind::Gauge,
            &[],
            Thresholds {
                warn: range(Some(10.0), Some(1.0)),
                alarm: Range::NONE,
            },
        )];
        assert!(matches!(
            with_metric(INVERTED).validate(),
            Err(SchemaError::BadMetric { .. })
        ));

        // The critical one does not contain the warning one.
        static NOT_NESTED: &[MetricDesc] = &[metric(
            ValueType::F32,
            MetricKind::Gauge,
            &[],
            Thresholds {
                warn: range(None, Some(80.0)),
                alarm: range(None, Some(50.0)),
            },
        )];
        assert!(matches!(
            with_metric(NOT_NESTED).validate(),
            Err(SchemaError::BadMetric { .. })
        ));

        // NaN as a bound: comparisons with it are always false, so the limit
        // would silently do nothing.
        static NAN: &[MetricDesc] = &[metric(
            ValueType::F32,
            MetricKind::Gauge,
            &[],
            Thresholds {
                warn: range(None, Some(f64::NAN)),
                alarm: Range::NONE,
            },
        )];
        assert!(matches!(
            with_metric(NAN).validate(),
            Err(SchemaError::BadMetric { .. })
        ));

        // Limits on an enum.
        static STATES: &[StateDesc] = &[StateDesc {
            code: 0,
            name: "A",
            severity: Severity::Normal,
        }];
        static BOTH: &[MetricDesc] = &[metric(
            ValueType::U64,
            MetricKind::State,
            STATES,
            Thresholds {
                warn: range(Some(0.0), Some(1.0)),
                alarm: Range::NONE,
            },
        )];
        assert!(matches!(
            with_metric(BOTH).validate(),
            Err(SchemaError::BadMetric { .. })
        ));

        // One-sided bounds and a fully open range are legitimate.
        static OPEN: &[MetricDesc] = &[metric(
            ValueType::F32,
            MetricKind::Gauge,
            &[],
            Thresholds {
                warn: range(None, Some(70.0)),
                alarm: range(Some(-273.15), None),
            },
        )];
        with_metric(OPEN).validate().expect("open bounds");
    }

    #[test]
    fn metric_index_is_stable_key_for_runtime_state() {
        // A metric's position is the key for what is stored alongside the
        // schema and never reaches disk (the limits). It has to match the order
        // in the array, or the limits would apply to the wrong metric.
        static M: &[MetricDesc] = &[
            MetricDesc {
                warn_if: None,
                alarm_if: None,
                id: MetricId(1),
                ..metric(ValueType::F32, MetricKind::Gauge, &[], Thresholds::NONE)
            },
            MetricDesc {
                warn_if: None,
                alarm_if: None,
                id: MetricId(9),
                name: "second",
                ..metric(ValueType::U64, MetricKind::Counter, &[], Thresholds::NONE)
            },
        ];
        let s = with_metric(M);
        s.validate().unwrap();
        assert_eq!(s.metric_index(MetricId(1)).unwrap().0, 0);
        assert_eq!(s.metric_index(MetricId(9)).unwrap().0, 1);
        assert_eq!(s.metric_index(MetricId(9)).unwrap().1.name, "second");
        assert!(s.metric_index(MetricId(5)).is_none());
    }

    #[test]
    fn degenerate_schemas_rejected() {
        static EVENTS: &[EventDesc] = &[];
        assert!(matches!(
            schema(EVENTS, 0).validate(),
            Err(SchemaError::ZeroVersion { .. })
        ));

        static NO_LANGS: &[Language] = &[];
        let s = Schema {
            languages: NO_LANGS,
            ..schema(EVENTS, 1)
        };
        assert!(matches!(s.validate(), Err(SchemaError::NoLanguages { .. })));

        static DUP_LANGS: &[Language] = &[Language("en"), Language("en")];
        let s = Schema {
            languages: DUP_LANGS,
            ..schema(EVENTS, 1)
        };
        assert!(matches!(
            s.validate(),
            Err(SchemaError::DuplicateLanguage { lang: "en", .. })
        ));
    }
}
